version: '3'
services:
jsondb:
image: clue/json-server
ports:

"3000:80"
volumes:
./data-layer/db.json:/data/db.json
command: ["--host", "0.0.0.0", "--watch", "/data/db.json"]
api:
build: .
ports:
"8080:8080"
environment:
DB_BASE_URL=http://jsondb:80/data/db.json
depends_on:
jsondb
